TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.0
  max_rotational_vel: 5.0
  min_in_place_rotational_vel: 0.4

  acc_lim_th: 2.0
  acc_lim_x: 1.0 #maximum is 2.0
  acc_lim_y: 0.0 #diff drive robot

  holonomic_robot: false

  yaw_goal_tolerance: 0.3
  xy_goal_tolerance: 0.15
  latch_xy_goal_tolerance: true

  dwa: false

  heading_lookahead: 0.5

  publish_cost_grid_pc: false

  pdist_scale: 0.6
  gdist_scale: 0.8
  occdist_scale: 0.5

  oscillation_reset_dist: 0.05
