controller_frequency:  5.0
controller_patience:  60.0
planner_patience:  60.0
#oscillation_timeout: 30.0
#oscillation_distance: 0.5

footprint_padding: 0.01
clearing_rotation_allowed: true
clearing_radius: 0.2

base_global_planner: navfn/NavfnROS
base_local_planner: dwa_local_planner/DWAPlannerROS

NavfnROS:
  allow_unknown: true

DWAPlannerROS:
  max_vel_x: 1.5
  min_vel_x: 0.0
  max_rotational_vel: 1.0
  min_in_place_rotational_vel: 0.4

  acc_lim_th: 0.5
  acc_lim_x: 0.3 #maximum is 2.0
  acc_lim_y: 0.0 #diff drive robot

  holonomic_robot: false

  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.2
  latch_xy_goal_tolerance: true

  heading_lookahead: 0.5

  publish_cost_grid_pc: false

  path_distance_bias: 32.0
#(double, default: 32.0)
#The weighting for how much the controller should stay close to the path it was given

  goal_distance_bias: 24.0
# (double, default: 24.0)
#The weighting for how much the controller should attempt to reach its local goal, also controls speed

  occdist_scale: 0.1
# (double, default: 0.01)
#The weighting for how much the controller should attempt to avoid obstacles

  forward_point_distance: 0.325
# (double, default: 0.325)
#The distance from the center point of the robot to place an additional scoring point, in meters

  oscillation_reset_dist: 0.05


